<?php /** @var $contact \Application\Entity\Contact */ ?>

<h2>Afficher un contact</h2>

<p>Prénom : <?= $this->escapeHtml($contact->getFirstName()) ?></p>
<p>Nom : <?= $this->escapeHtml($contact->getLastName()) ?></p>

<?php if ($contact->getEmail()) : ?>
    <p>Email : <?= $this->escapeHtml($contact->getEmail()) ?></p>
<?php endif; ?>

<?php if ($contact->getTelephone()) : ?>
    <p>Téléphone : <?= $this->escapeHtml($contact->getTelephone()) ?></p>
<?php endif; ?>
