<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle()->append('AddressBook')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <link rel="stylesheet" href="<?=$this->basePath('css/bootstrap.min.css')?>">
        <link rel="stylesheet" href="<?=$this->basePath('css/bootstrap-theme.min.css')?>">
        <link rel="stylesheet" href="<?=$this->basePath('css/style.css')?>">
        <link rel="shortcut icon" type="image/vnd.microsoft.icon" href="<?=$this->basePath() . '/img/favicon.ico'?>">

        <?= $this->headLink() ?>

        <?= $this->headStyle() ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        AddressBook
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?= $this->url('contact') ?>">Contacts</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?php // echo $this->plugin('\Bootstrap\View\Helper\Alert')('Coucou') ?>
            <?php // echo $this->plugin('btspAlert')('Coucou') ?>
            <?php // echo $this->btspAlert('Coucou') ?>
            <?= $this->content ?>
            <?= $this->btspButtonBack() ?>
            <hr>
            <footer>
                <p>&copy; <?= date('Y') ?> by Nous.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
