<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle()->append('AddressBook')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <link rel="stylesheet" href="<?= $this->basePath('css/bootstrap.min.css') ?>">
    <link rel="stylesheet" href="<?= $this->basePath('css/bootstrap-theme.min.css') ?>">
    <link rel="stylesheet" href="<?= $this->basePath('css/style.css') ?>">
    <link rel="shortcut icon" type="image/vnd.microsoft.icon" href="<?= $this->basePath() . '/img/favicon.ico' ?>">

    <?= $this->headLink() ?>

    <?= $this->headStyle() ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
    ?>
</head>
<body>
<?= $this->partial('layout/_menu.phtml') ?>
<div class="container">
    <?php // echo $this->plugin('\Bootstrap\View\Helper\Alert')('Coucou') ?>
    <?php // echo $this->plugin('btspAlert')('Coucou') ?>
    <?php // echo $this->btspAlert('Coucou'); ?>
    <?php
    // TODO créer une aide de vue pour n'appeller qu'une méthode
    // au lieu d'une boucle, ex :
    echo $this->btspAlertFlashMessenger('success');
    /*
    foreach ($this->flashMessenger()->getSuccessMessages() as $msg) {
        echo $this->btspAlert($msg);
    }
    */
    ?>
    <?= $this->content ?>
    <?= $this->btspButtonBack() ?>
    <hr>
    <footer>
        <p>&copy; <?= date('Y') ?> by Nous.</p>
    </footer>
</div>
<?= $this->inlineScript() ?>
</body>
</html>
